version: '3.8'

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "hokure"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5555:5432"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: hokure
      MINIO_ROOT_PASSWORD: goodstory87
    ports:
      - "9000:9000"
      - "9001:9001"  # Панель управления MinIO
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hokure
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      MINIO_URL: http://minio:9000
      MINIO_ACCESSKEY: hokure
      MINIO_SECRETKEY: goodstory87
      MINIO_BUCKET: my-bucket
    ports:
      - "8080:8080"

volumes:
  minio_data:

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

#mvn clean install && docker compose down -v && docker compose build && docker compose up